import { Vehicle, VehicleType } from './entities/vehicle.entity';

export const vehiclesMock: Vehicle[] = [
  {
    id: 1,
    type: VehicleType.Car,
    brand: 'Audi',
    model: 'A3',
    production_year: 2009,
    kilometers_driven: 80162,
    price: 8990,
  },
  {
    id: 2,
    type: VehicleType.Car,
    brand: 'Audi',
    model: 'A1',
    production_year: 2014,
    kilometers_driven: 114500,
    price: 9880,
  },
  {
    id: 3,
    type: VehicleType.Car,
    brand: 'Audi',
    model: 'A1 Sportback',
    production_year: 2014,
    kilometers_driven: 49750,
    price: 12880,
  },
  {
    id: 4,
    type: VehicleType.Car,
    brand: 'BMW',
    model: 'X6',
    production_year: 2018,
    kilometers_driven: 53887,
    price: 48160,
  },
  {
    id: 5,
    type: VehicleType.Car,
    brand: 'BMW',
    model: 'X3',
    production_year: 2013,
    kilometers_driven: 13660,
    price: 46330,
  },
  {
    id: 6,
    type: VehicleType.Motorcycle,
    brand: 'BMW',
    model: 'R 1250 GS',
    production_year: 2021,
    kilometers_driven: 5395,
    price: 18650,
  },
  {
    id: 7,
    type: VehicleType.Motorcycle,
    brand: 'BMW',
    model: 'R 1200 GS',
    production_year: 2009,
    kilometers_driven: 97300,
    price: 5250,
  },
  {
    id: 8,
    type: VehicleType.Motorcycle,
    brand: 'BMW',
    model: 'F 800 R',
    production_year: 2019,
    kilometers_driven: 6347,
    price: 8290,
  },
];
